# .cirrus.yml:
compute_engine_instance:
  # Image list available via
  # gcloud compute images list --project freebsd-org-cloud-dev --no-standard-images
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-2-release-amd64
  cpu: 1
  memory: 2G
  disk: 10


task:
  download_and_run_script:
  description: Build and test
    freebsd: 
      - pkg install -y git bastille  
    script:
      - git clone https://github.com/BastilleBSD/templates.git
      - cd templates
      - git rev-parse --abbrev-ref HEAD > branch.txt
      - read -r BRANCH <"branch.txt"
      - echo $BRANCH
      - rm branch.txt

      - git diff --dirstat main $BRANCH ./* > diff.txt
      - echo "*** diff.txt ***"
      - cat diff.txt

      - # Use sed to remove characters before the match pattern
      - match_pattern=" /"
      - sed "s/.*$match_pattern/$match_pattern/" "diff.txt" > changed.txt
      - echo "*** changed.txt ***"
      - cat changed.txt

      - read -r CHDIR <"changed.txt"
      - echo $CHDIR

      - cd $CHDIR
      - pwd
      - chmod +x ./test.sh
      - ./test.sh


